version: '3.8'
name: card-validation-system

services:
  card-validator-api:
    build:
      context: ./card.validator.api.v1
      dockerfile: Dockerfile
    ports:
      - "5105:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  card-validation-web:
    build:
      context: ./card.validation.app.v1
      dockerfile: Dockerfile
    ports:
      - "3105:3105"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5105
    depends_on:
      - card-validator-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
